import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen  ">
        <Nav />
        <div className='flex items-center justify-center p-24'>
          {children}
        </div>
      </body>
    </html>
  )
}
